

export const produtos = [
  
  {
    id: 0,
    nome: "Photon",
    resolucao: "2K (RGB)",
    marca: "Anycubic",
    tecnologia: "MSLA (RGB)",
    fonteLuz: "UV-LED",
    eixosXY: "0.047mm (2560x1440)",
    eixoZ: "0.00125mm",
    layerHeight: "0.01 - 0.2mm",
    velocidadeImpressao: "20mm/h",
    consumo: "40W",
    anoLancamento: "2018",
    tamanho: "22x20x40",
    porte: "medio",
    area: "115x65x155",
    peso: "6.6kg",
    conectividade: "USB",
    linearGuide: "simples",
    autoFill: false,
    autoWithdrawal: false,
    airPurifier: false,
    lcdProtector: false,
    heatVat: false,
    autoLeveling: false,
    buildPlate: "metal escovado",
    FEP: "normal",
    autoResume: false,
    imagem: "/img/anycubic/Anycubic Photon - impressao 3d resina.webp",
    description: "A impressora Photon da marca Anycubic é uma impressora de resina MSLA (RGB) que foi lançada em 2018. Possui uma resolução de 2K (RGB) e utiliza tecnologia UV-LED como fonte de luz. Seu tamanho é considerado médio, medindo 22x20x40 centímetros e tem uma área de impressão de 115x65x155 milímetros. Com um peso de 6.6kg, a impressora utiliza conectividade USB para transferência de dados. Ela possui uma resolução de eixos XY de 0.047mm (2560x1440) e uma precisão no eixo Z de 0.00125mm. A altura das camadas impressas pode variar entre 0.01 e 0.2mm, e a velocidade de impressão atinge 20mm/h. Seu consumo de energia é de 40W e conta com um sistema de guias lineares simples. A Photon utiliza uma build plate de metal escovado e F.E.P como filme de liberação."
    
},
{
    id: 1,
    nome: "Photon S",
    resolucao: "2K (RGB)",
    marca: "Anycubic",
    tecnologia: "MSLA (RGB)",
    fonteLuz: "UV-LED",
    eixosXY: "0.047mm (2560x1440)",
    eixoZ: "0.00125mm",
    layerHeight: "0.01 - 0.2mm",
    velocidadeImpressao: "20mm/h",
    consumo: "50W",
    anoLancamento: "2019",
    tamanho: "23x20x40",
    porte: "medio",
    area: "115x65x165",
    peso: "5.9kg",
    conectividade: "USB",
    linearGuide: "Dupla",
    autoFill: false,
    autoWithdrawal: false,
    airPurifier: true,
    lcdProtector: false,
    heatVat: false,
    autoLeveling: false,
    buildPlate: "metal escovado",
    FEP: "normal",
    autoResume: false,
    imagem: "/img/anycubic/Anycubic Photon S - impressao 3d resina.webp",
    description: "A impressora Photon S da marca Anycubic é uma impressora de resina MSLA (RGB) lançada em 2019. Possui uma resolução de 2K (RGB) e utiliza tecnologia UV-LED como fonte de luz. O tamanho da impressora é médio, medindo 23x20x40 centímetros, com uma área de impressão de 115x65x165 milímetros. Ela pesa 5.9kg e possui conectividade USB. A resolução dos eixos XY é de 0.047mm (2560x1440) e a precisão no eixo Z é de 0.00125mm. A altura das camadas impressas pode variar entre 0.01 e 0.2mm, com uma velocidade de impressão de 20mm/h. O consumo de energia é de 50W, e a impressora utiliza um sistema de guias lineares duplas. Ela conta com uma build plate de metal escovado e F.E.P como filme de liberação."
    
},
{
    id: 2,
    nome: "photon zero",
    resolucao: "480p",
    marca: "Anycubic",
    tecnologia: "MSLA",
    fonteLuz: "Matrix light source ",
    eixosXY: "0.1155mm (854x480)",
    eixoZ: "0.01mm",
    layerHeight: "0.01 - 0.2mm",
    velocidadeImpressao: "20mm/h",
    consumo: "30W",
    anoLancamento: "2020",
    tamanho: "18x19x36",
    porte: "pequeno",
    area: "97x54x150",
    peso: "4.7kg",
    conectividade: "USB",
    linearGuide: "simples",
    autoFill: false,
    autoWithdrawal: false,
    airPurifier: false,
    lcdProtector: false,
    heatVat: false,
    autoLeveling: false,
    buildPlate: "metal escovado",
    FEP: "normal",
    autoResume: false,
    imagem: "/img/anycubic/Anycubic Photon Zero - impressao 3d resina.webp",
    description: "A impressora Photon Zero da marca Anycubic é uma impressora de resina MSLA lançada em 2020. Ela possui uma resolução de 480p e utiliza a tecnologia Matrix Light Source como fonte de luz. Sendo uma impressora de tamanho pequeno, suas dimensões são de 18x19x36 centímetros, com uma área de impressão de 97x54x150 milímetros. Seu peso é de 4.7kg, e a conectividade é realizada via USB. A resolução dos eixos XY é de 0.1155mm (854x480), e a precisão no eixo Z é de 0.01mm. A altura das camadas impressas pode variar entre 0.01 e 0.2mm, com uma velocidade de impressão de 20mm/h. O consumo de energia é de 30W, e a impressora utiliza um sistema de guias lineares simples. Ela possui uma build plate de metal escovado e utiliza F.E.P como filme de liberação."
    
},
{
    id: 3,
    nome: "photon mono",
    resolucao: "2K",
    marca: "Anycubic",
    tecnologia: "MSLA",
    fonteLuz: "Matrix light source ",
    eixosXY: "0.051mm (2560x1620)",
    eixoZ: "0.01mm",
    layerHeight: "0.01 - 0.15mm",
    velocidadeImpressao: "50mm/h",
    consumo: "45W",
    anoLancamento: "2020",
    tamanho:"222x227x383",
    porte: "medio",
    area: "130x80x165",
    peso: 4.25,
    conectividade: "USB",
    linearGuide: "simples",
    autoFill: false,
    autoWithdrawal: false,
    airPurifier: false,
    lcdProtector: false,
    heatVat: false,
    autoLeveling: false,
    buildPlate: "metal escovado",
    FEP: "normal",
    autoResume: false,
    imagem: "/img/anycubic/Anycubic Photon Mono - impressao 3d resina.webp",
    description: "A impressora Photon Mono da marca Anycubic é uma impressora de resina MSLA lançada em 2020. Ela oferece uma resolução de 2K e utiliza a tecnologia Matrix Light Source como fonte de luz. Com um tamanho médio, suas dimensões são de 222x227x383 centímetros e possui uma área de impressão de 130x80x165 milímetros. Com um peso de 4.25kg, a conectividade é realizada via USB. A resolução dos eixos XY é de 0.051mm (2560x1620), e a precisão no eixo Z é de 0.01mm. A altura das camadas impressas pode variar entre 0.01 e 0.15mm, com uma impressionante velocidade de impressão de 50mm/h. O consumo de energia é de 45W, e a impressora utiliza um sistema de guias lineares simples. Ela possui uma build plate de metal escovado e utiliza F.E.P como filme de liberação."
    
},
{
    id: 4,
    nome: "photon mono X",
    resolucao: "4K",
    marca: "Anycubic",
    tecnologia: "MSLA",
    fonteLuz: "Matrix light source ",
    eixosXY: "0.050mm (3840x2420)",
    eixoZ: "0.01mm",
    layerHeight: "0.01 - 0.15mm",
    velocidadeImpressao: "60mm/h",
    consumo: "120W",
    anoLancamento: "2020",
    tamanho: "27x29x47",
    porte: "grande",
    area: "192x120x245",
    peso: "10.75",
    conectividade: "USB / Wi-fi",
    linearGuide: "Dupla",
    autoFill: false,
    autoWithdrawal: false,
    airPurifier: false,
    lcdProtector: false,
    heatVat: false,
    autoLeveling: false,
    buildPlate: "metal escovado",
    FEP: "normal",
    autoResume: false,
    imagem: "/img/anycubic/Anycubic Photon Mono X - impressao 3d resina.webp",
    description: "A impressora Photon Mono X da marca Anycubic é uma impressora de resina MSLA lançada em 2020. Ela oferece uma incrível resolução de 4K e utiliza a tecnologia Matrix Light Source como fonte de luz. Com um tamanho grande, suas dimensões são de 27x29x47 centímetros e possui uma área de impressão de 192x120x245 milímetros. Com um peso de 10.75kg, a conectividade é possível tanto via USB quanto Wi-Fi. A resolução dos eixos XY é de 0.050mm (3840x2420), e a precisão no eixo Z é de 0.01mm. A altura das camadas impressas pode variar entre 0.01 e 0.15mm, com uma impressionante velocidade de impressão de 60mm/h. No entanto, vale ressaltar que o consumo de energia é de 120W, o que é mais alto em comparação com outras impressoras.A impressora Photon Mono X utiliza um sistema de guias lineares duplas para maior estabilidade e uma build plate de metal escovado. Utiliza F.E.P como filme de liberação."
    
},
{
    id: 5,
    nome: "photon mono SE",
    resolucao: "2K",
    marca: "Anycubic",
    tecnologia: "MSLA",
    fonteLuz: "Matrix light source ",
    eixosXY: "0.051mm (2560x1620)",
    eixoZ: "0.01mm",
    layerHeight: "0.01 - 0.15mm",
    velocidadeImpressao: "80mm/h",
    consumo: "55W",
    anoLancamento: "2020",
    tamanho:"22x20x40",
    porte: "medio",
    area: "130x78x160",
    peso: 8.2,
    conectividade: "USB / Wi-fi",
    linearGuide: "Dupla",
    autoFill: false,
    autoWithdrawal: false,
    airPurifier: true,
    lcdProtector: false,
    heatVat: false,
    autoLeveling: false,
    buildPlate: "metal escovado",
    FEP: "normal",
    autoResume: false,
    imagem: "/img/anycubic/Anycubic Photon Mono SE - impressao 3d resina.webp",
    description: "A impressora Photon Mono SE da marca Anycubic é uma impressora de resina MSLA lançada em 2020. Ela oferece uma resolução de 2K e utiliza a tecnologia Matrix Light Source como fonte de luz. Com um tamanho médio, suas dimensões são de 22x20x40 centímetros e possui uma área de impressão de 130x78x160 milímetros. Ela pesa 8.2kg e possui conectividade via USB e Wi-Fi, o que é uma vantagem para gerenciar a impressão de forma conveniente. A resolução dos eixos XY é de 0.051mm (2560x1620), e a precisão no eixo Z é de 0.01mm. A altura das camadas impressas pode variar entre 0.01 e 0.15mm, com uma velocidade de impressão impressionante de 80mm/h. O consumo de energia é de 55W, o que está em um nível moderado. A impressora Photon Mono SE utiliza um sistema de guias lineares duplas para maior estabilidade e possui uma build plate de metal escovado. Utiliza F.E.P como filme de liberação. Um recurso notável é a presença de um sistema de purificação de ar (air purifier), o que ajuda a melhorar a qualidade do ambiente durante a impressão."
    
},
{
    id: 6,
    nome: "photon Ultra",
    resolucao: "720p",
    marca: "Anycubic",
    tecnologia: "DLP",
    fonteLuz: "UV-LED Projector",
    eixosXY: "0.08mm (1280x720)",
    eixoZ: "0.01mm",
    layerHeight: "0.01 - 0.15mm",
    velocidadeImpressao: "50mm/h",
    consumo: "15W",
    anoLancamento: "2021",
    tamanho: "22x22x38",
    porte: "medio",
    area: "102x57x165",
    peso: "4",
    conectividade: "USB",
    linearGuide: "simples",
    autoFill: false,
    autoWithdrawal: false,
    airPurifier: false,
    lcdProtector: false,
    heatVat: false,
    autoLeveling: false,
    buildPlate: "Gravada a laser",
    FEP: "normal",
    autoResume: false,
    imagem: "/img/anycubic/Anycubic Photon Ultra - impressao 3d resina.webp",
    description: "A impressora Photon Ultra da marca Anycubic é uma impressora de resina DLP lançada em 2021. Ela oferece uma resolução de 720p e utiliza a tecnologia de projeção (projetor UV-LED) como fonte de luz. Com um tamanho médio, suas dimensões são de 22x22x38 centímetros e possui uma área de impressão de 102x57x165 milímetros. Ela pesa 4kg e possui conectividade via USB. A resolução dos eixos XY é de 0.08mm (1280x720), e a precisão no eixo Z é de 0.01mm. A altura das camadas impressas pode variar entre 0.01 e 0.15mm, com uma velocidade de impressão de 50mm/h. O consumo de energia é baixo, de apenas 15W, o que a torna uma opção eficiente em termos de consumo energético. A impressora Photon Ultra utiliza um sistema de guias lineares simples e uma build plate gravada a laser. Utiliza como F.E.P como filme de liberação. "
    
},
{
    id: 7,
    nome: "photon mono SQ",
    resolucao: "3k",
    marca: "Anycubic",
    tecnologia: "MSLA",
    fonteLuz: "Matrix light source ",
    eixosXY: "0.50mm (2560x2400)",
    eixoZ: "0.01mm",
    layerHeight: "0.05 - 0.15mm",
    velocidadeImpressao: "50mm/h",
    consumo: "66W",
    anoLancamento: "2021",
    tamanho:"22x27x44",
    porte: "medio",
    area: "128x120x200",
    peso: 8.5,
    conectividade: "USB",
    linearGuide: "simples",
    autoFill: false,
    autoWithdrawal: false,
    airPurifier: false,
    lcdProtector: true,
    heatVat: false,
    autoLeveling: false,
    buildPlate: "Gravado a laser",
    FEP: "normal",
    autoResume: false,
    imagem: "/img/anycubic/anycubic photon mono SQ - impressao 3d resina.webp",
    description: "A impressora Photon Mono SQ da marca Anycubic é uma impressora de resina MSLA lançada em 2021. Ela oferece uma resolução de 3K e utiliza a tecnologia Matrix Light Source como fonte de luz. Com um tamanho médio, suas dimensões são de 22x27x44 centímetros e possui uma área de impressão de 128x120x200 milímetros. Ela pesa 8.5kg e possui conectividade via USB. A resolução dos eixos XY é de 0.50mm (2560x2400), e a precisão no eixo Z é de 0.01mm. A altura das camadas impressas pode variar entre 0.05 e 0.15mm, com uma velocidade de impressão de 50mm/h. O consumo de energia é de 66W. A impressora Photon Mono SQ utiliza um sistema de guias lineares simples e possui uma build plate gravada a laser. O F.E.P é utilizado como filme de liberação. Além disso, essa impressora é equipada com um protetor de LCD para evitar possiveis arranhões."

},
{
    id: 8,
    nome: "photon mono (4K)",
    resolucao: "4K",
    marca: "Anycubic",
    tecnologia: "MSLA",
    fonteLuz: "Matrix paralelt source ",
    eixosXY: "35um (3840x2400)",
    eixoZ: "0.01mm",
    layerHeight: "0.01 - 0.15mm",
    velocidadeImpressao: "50mm/h",
    consumo: "45W",
    anoLancamento: "2021",
    tamanho:"22x22x38",
    porte: "medio",
    area: "132x80x165",
    peso: 4.25,
    conectividade: "USB",
    linearGuide: "simples",
    autoFill: false,
    autoWithdrawal: false,
    airPurifier: false,
    lcdProtector: true,
    heatVat: false,
    autoLeveling: false,
    buildPlate: "metal escovado",
    FEP: "normal",
    autoResume: false,
    imagem: "/img/anycubic/Anycubic Photon Mono (4K) - impressao 3d resina.webp",
    description: "A impressora Photon Mono (4K) da marca Anycubic é uma impressora de resina MSLA lançada em 2021. Ela oferece uma impressionante resolução de 4K e utiliza a tecnologia Matrix Parallel Source como fonte de luz. Com um tamanho médio, suas dimensões são de 22x22x38 centímetros e possui uma área de impressão de 132x80x165 milímetros. Ela pesa 4.25kg e possui conectividade via USB. A resolução dos eixos XY é de 35 micrômetros (3840x2400), e a precisão no eixo Z é de 0.01mm. A altura das camadas impressas pode variar entre 0.01 e 0.15mm, com uma velocidade de impressão de 50mm/h. O consumo de energia é de 45W. A impressora Photon Mono (4K) utiliza um sistema de guias lineares simples e possui uma build plate de metal escovado. Utiliza F.E.P como filme de liberação. Além disso, essa impressora é equipada com uma pelicula de proteção de LCD, para evitar possiveis riscos e/ou manchas."
    
},
{
    id: 9,
    nome: "photon mono X (6k)",
    resolucao: "6k",
    marca: "Anycubic",
    tecnologia: "MSLA",
    fonteLuz: "Matrix paralelt source ",
    eixosXY: "34.4um (5760x3600)",
    eixoZ: "0.01mm",
    layerHeight: "0.01 - 0.15mm",
    velocidadeImpressao: "60mm/h",
    consumo: "120W",
    anoLancamento: "2021",
    tamanho: "27x29x47",
    porte: "grande",
    area: "197x122x245",
    peso: "10.75",
    conectividade: "USB / Wi-fi",
    linearGuide: "Dupla",
    autoFill: false,
    autoWithdrawal: false,
    airPurifier: false,
    lcdProtector: true,
    heatVat: false,
    autoLeveling: false,
    buildPlate: "Gravada a laser",
    FEP: "normal",
    autoResume: false,
    imagem: "/img/anycubic/Anycubic Photon Mono X (6K) - impressao 3d resina.webp",
    description: "A impressora Photon Mono X (6K) da marca Anycubic é uma impressora de resina MSLA lançada em 2021. Ela oferece uma impressionante resolução de 6K e utiliza a tecnologia Matrix Parallel Source como fonte de luz. Com um tamanho grande, suas dimensões são de 27x29x47 centímetros e possui uma área de impressão de 197x122x245 milímetros. Ela pesa 10.75kg e possui conectividade via USB e Wi-Fi, o que é uma vantagem para gerenciar a impressão de forma conveniente. A resolução dos eixos XY é de 34.4 micrômetros (5760x3600), e a precisão no eixo Z é de 0.01mm. A altura das camadas impressas pode variar entre 0.01 e 0.15mm, com uma velocidade de impressão de 60mm/h. O consumo de energia é de 120W, o que é mais alto em comparação com outras impressoras. A impressora Photon Mono X (6K) utiliza um sistema de guias lineares duplas para maior estabilidade e possui uma build plate gravada a laser. Utiliza F.E.P como filme de liberação. Além disso, essa impressora é equipada com proteção de LCD para evitar possiveis arranhões e/ou manchas.    "
    
},
{
    id: 10,
    nome: "Photon Mono X 6k T. Edit",
    resolucao: "6k",
    marca: "Anycubic",
    tecnologia: "MSLA",
    fonteLuz: "Matrix paralelt source ",
    eixosXY: "34.4um (5760x3600)",
    eixoZ: "0.01mm",
    layerHeight: "0.01 - 0.15mm",
    velocidadeImpressao: "60mm/h",
    consumo: "120W",
    anoLancamento: "2022",
    tamanho: "27x29x47",
    porte: "grande",
    area: "197x122x245",
    peso: "10.75",
    conectividade: "USB / Wi-fi",
    linearGuide: "Dupla",
    autoFill: false,
    autoWithdrawal: false,
    airPurifier: false,
    lcdProtector: true,
    heatVat: false,
    autoLeveling: false,
    buildPlate: "metal escovado",
    FEP: "normal",
    autoResume: false,
    imagem: "/img/anycubic/Anycubic Photon Mono X 6K - Limited Edition.webp",
    description: "Resumo em breve."
    
},
{
    id: 11,
    nome: "Photon D2",
    resolucao: "2K",
    marca: "Anycubic",
    tecnologia: "DLP",
    fonteLuz: "UV-LED Projector",
    eixosXY: "51um (2560x1440)",
    eixoZ: "0.01mm",
    layerHeight: "0.01 - 0.15mm",
    velocidadeImpressao: "50mm/h",
    consumo: "15W",
    anoLancamento: "2022",
    tamanho: "23x22x43",
    porte: "medio",
    area: "130x73x165",
    peso: "5",
    conectividade: "USB",
    linearGuide: "simples",
    autoFill: false,
    autoWithdrawal: false,
    airPurifier: false,
    lcdProtector: false,
    heatVat: false,
    autoLeveling: false,
    buildPlate: "Gravada a laser",
    FEP: "normal",
    autoResume: false,
    imagem: "/img/anycubic/Anycubic Photon D2 - impressao 3d resina.webp",
    description: "Resumo em breve."
    
},
{
    id: 12,
    nome: "Photon M3",
    resolucao: "4K",
    marca: "Anycubic",
    tecnologia: "MSLA",
    fonteLuz: "Matrix paralelt source ",
    eixosXY: "40um (4096x2560)",
    eixoZ: "0.01mm",
    layerHeight: "0.01 - 0.15mm",
    velocidadeImpressao: "50mm/h",
    consumo: "55W",
    anoLancamento: "2022",
    tamanho: "26x25x42",
    porte: "medio",
    area: "163x102x180",
    peso: "7",
    conectividade: "USB",
    linearGuide: "simples",
    autoFill: false,
    autoWithdrawal: false,
    airPurifier: false,
    lcdProtector: true,
    heatVat: false,
    autoLeveling: false,
    buildPlate: "Gravada a laser",
    FEP: "normal",
    autoResume: false,
    imagem: "/img/anycubic/Anycubic Photon M3 - impressao 3d resina.webp",
    description: "Resumo em breve."
    
},
{
    id: 13,
    nome: "Photon M3 Plus",
    resolucao: "6k",
    marca: "Anycubic",
    tecnologia: "MSLA",
    fonteLuz: "Matrix paralelt source ",
    eixosXY: "34.4um (5760x3600)",
    eixoZ: "0.01mm",
    layerHeight: "0.01 - 0.15mm",
    velocidadeImpressao: "100mm/h",
    consumo: "120W",
    anoLancamento: "2022",
    tamanho: "36x29x47",
    porte: "grande",
    area: "197x122x245",
    peso: "12",
    conectividade: "USB / Wi-fi / RJ-45",
    linearGuide: "Dupla",
    autoFill: true,
    autoWithdrawal: false,
    airPurifier: false,
    lcdProtector: true,
    heatVat: false,
    autoLeveling: false,
    buildPlate: "Gravada a laser",
    FEP: "normal",
    autoResume: false,
    imagem: "/img/anycubic/Anycubic Photon M3 Plus - impressao 3d resina.webp",
    description: "Resumo em breve."
    
},
{
    id: 14,
    nome: "Photon M3 Max",
    resolucao: "7K",
    marca: "Anycubic",
    tecnologia: "MSLA",
    fonteLuz: "Matrix paralelt source ",
    eixosXY: "46um (6480x3600)",
    eixoZ: "0.01mm",
    layerHeight: "0.01 - 0.1mm",
    velocidadeImpressao: "60mm/h",
    consumo: "120W",
    anoLancamento: "2022",
    tamanho: "40x40x59",
    porte: "grande",
    area: "298x164x300",
    peso: "21",
    conectividade: "USB",
    linearGuide: "Dupla",
    autoFill: true,
    autoWithdrawal: false,
    airPurifier: false,
    lcdProtector: true,
    heatVat: false,
    autoLeveling: false,
    buildPlate: "Gravada a laser",
    FEP: "normal",
    autoResume: false,
    imagem: "/img/anycubic/Anycubic Photon M3 Max - impressao 3d resina.webp",
    description: "Resumo em breve."
    
},
{
    id: 15,
    nome: "Photon M3 Premium",
    resolucao: "8K",
    marca: "Anycubic",
    tecnologia: "MSLA",
    fonteLuz: "Matrix paralelt source ",
    eixosXY: "28.5um (7680x4320)",
    eixoZ: "0.01mm",
    layerHeight: "0.01 - 0.1mm",
    velocidadeImpressao: "95mm/h",
    consumo: "110W",
    anoLancamento: "2022",
    tamanho: "32x35x62",
    porte: "grande",
    area: "218x123x250",
    peso: "19",
    conectividade: "USB / Wi-fi",
    linearGuide: "Dupla",
    autoFill: false,
    autoWithdrawal: false,
    airPurifier: true,
    lcdProtector: true,
    heatVat: false,
    autoLeveling: false,
    buildPlate: "Gravada a laser",
    FEP: "nromal",
    autoResume: false,
    imagem: "/img/anycubic/Anycubic Photon M3 Premium - impressao 3d resina.webp",
    description: "Resumo em breve."
    
},
{
    id: 16,
    nome: "photon mono X2",
    resolucao: "4K",
    marca: "Anycubic",
    tecnologia: "MSLA",
    fonteLuz: "Matrix paralelt source ",
    eixosXY: "48um (4096x2560)",
    eixoZ: "0.01mm",
    layerHeight: "0.01 - 0.15mm",
    velocidadeImpressao: "60mm/h",
    consumo: "100W",
    anoLancamento: "2022",
    tamanho: "29x26x41",
    porte: "grande",
    area: "196x122x200",
    peso: "7",
    conectividade: "USB / Wi-fi (não incluso)",
    linearGuide: "Dupla",
    autoFill: false,
    autoWithdrawal: false,
    airPurifier: false,
    lcdProtector: true,
    heatVat: false,
    autoLeveling: false,
    buildPlate: "Gravada a laser",
    FEP: "normal",
    autoResume: false,
    imagem: "/img/anycubic/Anycubic Photon Mono X2 - impressao 3d resina.webp",
    description: "Resumo em breve."
    
},
{
    id: 17,
    nome: "Photon Mono X 6ks",
    resolucao: "6k",
    marca: "Anycubic",
    tecnologia: "MSLA",
    fonteLuz: "LighTurbo Matrix",
    eixosXY: "5760x3600",
    eixoZ: "0.01mm",
    layerHeight: "0.01 - 0.15mm",
    velocidadeImpressao: "60mm/h",
    consumo: "80W",
    anoLancamento: "2023",
    tamanho:"29x26x41",
    porte: "grande",
    area: "195x122x200",
    peso: "8.5kg",
    conectividade: "USB",
    linearGuide: "Dupla",
    autoFill: false,
    autoWithdrawal: false,
    airPurifier: false,
    lcdProtector: true,
    heatVat: false,
    autoLeveling: false,
    buildPlate: "Gravada a laser",
    FEP: "normal",
    resinDetection: false,
    autoResume: false,
    imagem: "/img/anycubic/Anycubic Photon Mono 6Ks - impressao 3d resina.webp",
    description: "Resumo em breve."
    
},
{
    id: 18,
    nome: "photon mono 2",
    resolucao: "4K",
    marca: "Anycubic",
    tecnologia: "MSLA",
    fonteLuz: "LighTurbo Matrix",
    eixosXY: "4096x2560",
    eixoZ: "0.01mm",
    layerHeight: "0.01 - 0.15mm",
    velocidadeImpressao: "50mm/h",
    consumo: "48W",
    anoLancamento: "2023",
    tamanho: "22x23x39",
    porte: "medio",
    area: "143x89x165",
    peso: "4kg",
    conectividade: "USB",
    linearGuide: "simples",
    autoFill: false,
    autoWithdrawal: false,
    airPurifier: false,
    lcdProtector: true,
    heatVat: false,
    autoLeveling: false,
    buildPlate: "Gravada a laser",
    FEP: "normal",
    autoResume: false,
    imagem: "/img/anycubic/Anycubic Photon Mono 2 - impressao 3d resina.webp",
    description: "Resumo em breve."
    
},
{
    id: 19,
    nome: "Photon M5",
    resolucao: "12K",
    marca: "Anycubic",
    tecnologia: "MSLA",
    fonteLuz: "LighTurbo Matrix",
    eixosXY: "11520x5120",
    eixoZ: "0.01mm",
    layerHeight: "0.01 - 0.15mm",
    velocidadeImpressao: "50mm/h",
    consumo: "100W",
    anoLancamento: "2023",
    tamanho:"29x27x46",
    porte: "grande",
    area: "218x122x200",
    peso: "8.6kg",
    conectividade: "USB + Wi-fi",
    linearGuide: "Dupla",
    autoFill: false,
    autoWithdrawal: false,
    airPurifier: false,
    lcdProtector: true,
    heatVat: false,
    autoLeveling: false,
    buildPlate: "Gravada a laser",
    FEP: "normal",
    resinDetection: false,
    autoResume: false,
    imagem: "/img/anycubic/Photon M5 - impressao 3d resina.webp",
    description: "Resumo em breve."
    
},
{
    id: 20,
    nome: "Photon M5s",
    resolucao: "12K",
    marca: "Anycubic",
    tecnologia: "MSLA",
    fonteLuz: "LighTurbo Matrix",
    eixosXY: "11520x5120",
    eixoZ: "0.01mm",
    layerHeight: "0.01 - 0.15mm",
    velocidadeImpressao: "105mm/h",
    consumo: "100W",
    anoLancamento: "2023",
    tamanho:"29x27x46",
    porte: "grande",
    area: "218x122x200",
    peso: "8.9kg",
    conectividade: "USB / Wi-fi",
    linearGuide: "Dupla",
    autoFill: false,
    autoWithdrawal: false,
    airPurifier: false,
    lcdProtector: true,
    heatVat: false,
    autoLeveling: true,
    buildPlate: "Gravada a laser",
    FEP: "normal",
    resinDetection: true,
    autoResume: false,
    imagem: "/img/anycubic/Photon M5s - impressao 3d resina.webp",
    description: "Resumo em breve."
    
},







  /* CREALITY  */
  {
    id: 21,
    nome: "Creality LD-001",
    resolucao: "2K (RGB)",
    marca: "Creality",
    tecnologia: "MSLA (RGB)",
    fonteLuz: "UV-LED",
    eixosXY: "47um(2560x1440)",
    eixoZ: "0.02",
    layerHeight: "0.02 - 0.05mm",
    velocidadeImpressao: "20mm/h",
    consumo: "90W",
    anoLancamento: "2018",
    tamanho: "22x24x36",
    porte: "pequena",
    area: "120x70x120",
    peso: "6.4",
    conectividade: "USB",
    linearGuide: "simples",
    autoFill: false,
    autoWithdrawal: false,
    airPurifier: false,
    lcdProtector: false,
    heatVat: false,
    autoLeveling: false,
    buildPlate: "metal escovado",
    FEP: "normal",
    autoResume: false,
    imagem: "/img/creality",
    description: "Resumo em breve.",
    autoResume: false,
    imagem: "/img/creality/Creality LD-001 - impressao 3d resina.webp",
    description: "Resumo em breve."
    
},
{
    id: 22,
    nome: "Creality LD-002R",
    resolucao: "2K (RGB)",
    marca: "Creality",
    tecnologia: "MSLA (RGB)",
    fonteLuz: "UV-LED",
    eixosXY: "47um(2560x1440)",
    eixoZ: "0.03",
    layerHeight: "0.03 - 0.05mm",
    velocidadeImpressao: "6 - 18s",
    consumo: "72W",
    anoLancamento: "2020",
    tamanho: "22x22x40",
    porte: "medio",
    area: "119x65x160",
    peso: "7",
    conectividade: "USB",
    linearGuide: "simples",
    autoFill: false,
    autoWithdrawal: false,
    airPurifier: false,
    lcdProtector: false,
    heatVat: false,
    autoLeveling: false,
    buildPlate: "metal escovado",
    FEP: "normal",
    autoResume: false,
    imagem: "/img/creality/LD-002R - impressao 3d resina.webp",
    description: "Resumo em breve."
    
},
{
    id: 23,
    nome: "Creality LD-002H",
    resolucao: "2K",
    marca: "Creality",
    tecnologia: "MSLA",
    fonteLuz: "UV-LED",
    eixosXY: "51um(2560x1620)",
    eixoZ: "0.03",
    layerHeight: "0.03 - 0.05mm",
    velocidadeImpressao: "20mm/h",
    consumo: "72W",
    anoLancamento: "2020",
    tamanho: "22x22x40",
    porte: "medio",
    area: "130x82x160",
    peso: "7",
    conectividade: "USB",
    linearGuide: "simples",
    autoFill: false,
    autoWithdrawal: false,
    airPurifier: false,
    lcdProtector: false,
    heatVat: false,
    autoLeveling: false,
    buildPlate: "metal escovado",
    FEP: "normal",
    autoResume: false,
    imagem: "/img/creality/LD-002H - impressao 3d resina.webp",
    description: "Resumo em breve."
    
},
{
    id: 24,
    nome: "Creality LD-006",
    resolucao: "4K",
    marca: "Creality",
    tecnologia: "MSLA",
    fonteLuz: "Matrix Light Source",
    eixosXY: "50um(3840x2400)",
    eixoZ: "0.01",
    layerHeight: "0.01 - 0.1mm",
    velocidadeImpressao: "1-4s",
    consumo: "250W",
    anoLancamento: "2021",
    tamanho: "32x29x50",
    porte: "grande",
    area: "192x120x250",
    peso: "13.5",
    conectividade: "USB",
    linearGuide: "Dupla",
    autoFill: false,
    autoWithdrawal: false,
    airPurifier: true,
    lcdProtector: false,
    heatVat: false,
    autoLeveling: false,
    buildPlate: "metal escovado",
    FEP: "normal",
    autoResume: false,
    imagem: "/img/creality/LD-006 - impressao 3d resina.webp",
    description: "Resumo em breve."
    
},
{
    id: 25,
    nome: "Halot-Lite",
    resolucao: "4K",
    marca: "Creality",
    tecnologia: "MSLA",
    fonteLuz: "Integral Light Source",
    eixosXY: "50um(3840x2400)",
    eixoZ: "0.01",
    layerHeight: "0.01 - 0.2mm",
    velocidadeImpressao: "1-4s",
    consumo: "250W",
    anoLancamento: "2021",
    tamanho: "33x30x57",
    porte: "grande",
    area: "192x120x200",
    peso: "10.6",
    conectividade: "USB / Wi-fi",
    linearGuide: "simples",
    autoFill: false,
    autoWithdrawal: false,
    airPurifier: true,
    lcdProtector: false,
    heatVat: false,
    autoLeveling: false,
    buildPlate: "metal escovado",
    FEP: "normal",
    autoResume: false,
    imagem: "/img/creality/Halot Lite - impressao 3d resina.webp",
    description: "Resumo em breve."
    
},
{
    id: 26,
    nome: "Halot-Sky",
    resolucao: "4K",
    marca: "Creality",
    tecnologia: "MSLA",
    fonteLuz: "Integral Light Source",
    eixosXY: "50um(3840x2400)",
    eixoZ: "0.01",
    layerHeight: "0.01 - 0.2mm",
    velocidadeImpressao: "1-4s",
    consumo: "250W",
    anoLancamento: "2021",
    tamanho: "34x29x55",
    porte: "grande",
    area: "192x120x200",
    peso: "16.5",
    conectividade: "USB / Wi-fi",
    linearGuide: "Dupla",
    autoFill: false,
    autoWithdrawal: false,
    airPurifier: true,
    lcdProtector: false,
    heatVat: false,
    autoLeveling: false,
    buildPlate: "metal escovado",
    FEP: "normal",
    autoResume: false,
    imagem: "/img/creality/Halot Sky - impressao 3d resina.webp",
    description: "Resumo em breve."
    
},
{
    id: 27,
    nome: "Halot-One",
    resolucao: "2K",
    marca: "Creality",
    tecnologia: "MSLA",
    fonteLuz: "Integral Light Source",
    eixosXY: "50um(2560x1620)",
    eixoZ: "0.01",
    layerHeight: "0.01 - 0.2mm",
    velocidadeImpressao: "1-4s",
    consumo: "100W",
    anoLancamento: "2021",
    tamanho: "22x22x40",
    porte: "medio",
    area: "127x80x160",
    peso: "7.1",
    conectividade: "USB / Wi-fi",
    linearGuide: "simples",
    autoFill: false,
    autoWithdrawal: false,
    airPurifier: true,
    lcdProtector: false,
    heatVat: false,
    autoLeveling: false,
    buildPlate: "metal escovado",
    FEP: "normal",
    autoResume: false,
    imagem: "/img/creality/Halot One - impressao 3d resina.webp",
    description: "Resumo em breve."
    
},
{
    id: 28,
    nome: "Halot-Ray",
    resolucao: "6k",
    marca: "Creality",
    tecnologia: "MSLA",
    fonteLuz: "Integral Light Source",
    eixosXY: "30um(5760x3600)",
    eixoZ: "0.01",
    layerHeight: "0.01 - 0.2mm",
    velocidadeImpressao: "1-4s",
    consumo: "250W",
    anoLancamento: "2022",
    tamanho: "33x30x57",
    porte: "grande",
    area: "198x123x210",
    peso: "11.7",
    conectividade: "USB / Wi-fi",
    linearGuide: "Dupla",
    autoFill: false,
    autoWithdrawal: false,
    airPurifier: true,
    lcdProtector: false,
    heatVat: false,
    autoLeveling: false,
    buildPlate: "metal escovado",
    FEP: "normal",
    autoResume: false,
    imagem: "/img/creality/Halot Ray - impressao 3d resina.webp",
    description: "Resumo em breve."
    
},
{
    id: 29,
    nome: "Halot-One Pro",
    resolucao: "2K",
    marca: "Creality",
    tecnologia: "MSLA",
    fonteLuz: "Integral Light Source",
    eixosXY: "51um(2560x1620)",
    eixoZ: "0.01",
    layerHeight: "0.01 - 0.2mm",
    velocidadeImpressao: "1-4s",
    consumo: "100W",
    anoLancamento: "2022",
    tamanho: "23x24x41",
    porte: "medio",
    area: "130x122x160",
    peso: "6.9",
    conectividade: "USB / Wi-fi",
    linearGuide: "Dupla",
    autoFill: false,
    autoWithdrawal: false,
    airPurifier: true,
    lcdProtector: false,
    heatVat: false,
    autoLeveling: false,
    buildPlate: "metal escovado",
    FEP: "normal",
    autoResume: false,
    imagem: "/img/creality/Halot One Pro - impressao 3d resina.webp",
    description: "Resumo em breve."
    
},
{
    id: 30,
    nome: "Halot-One Plus",
    resolucao: "4K",
    marca: "Creality",
    tecnologia: "MSLA",
    fonteLuz: "Integral Light Source",
    eixosXY: "51um(4320*2560)",
    eixoZ: "0.01",
    layerHeight: "0.01 - 0.2mm",
    velocidadeImpressao: "1-4s",
    consumo: "100W",
    anoLancamento: "2022",
    tamanho: "23x24x41",
    porte: "medio",
    area: "172x102x160",
    peso: "6.8",
    conectividade: "USB / Wi-fi",
    linearGuide: "Dupla",
    autoFill: false,
    autoWithdrawal: false,
    airPurifier: true,
    lcdProtector: false,
    heatVat: false,
    autoLeveling: false,
    buildPlate: "metal escovado",
    FEP: "normal",
    autoResume: false,
    imagem: "/img/creality/Halot One Plus - impressao 3d resina.webp",
    description: "Resumo em breve."
    
},
{
    id: 31,
    nome: "Halot-Mage",
    resolucao: "8K",
    marca: "Creality",
    tecnologia: "MSLA",
    fonteLuz: "Integral Light Source",
    eixosXY: "7680*4320",
    eixoZ: "0.05",
    layerHeight: "0.05 - 0.15mm",
    velocidadeImpressao: "1-5s/layer",
    consumo: "100W",
    anoLancamento: "2023",
    tamanho: "33x27x60",
    porte: "grande",
    area: "228x128x230",
    peso: "11.7kg",
    conectividade: "USB",
    linearGuide: "Dupla",
    autoFill: false,
    autoWithdrawal: false,
    airPurifier: true,
    lcdProtector: true,
    heatVat: false,
    autoLeveling: false,
    buildPlate: "metal escovado",
    FEP: "normal",
    autoResume: false,
    imagem: "/img/creality/Creality Halot-Mage - impressao 3d resina.webp",
    description: "Resumo em breve."
    
},
{
    id: 32,
    nome: "Halot-Mage Pro",
    resolucao: "8K",
    marca: "Creality",
    tecnologia: "MSLA",
    fonteLuz: "Integral Light Source 3.0",
    eixosXY: "7680*4320",
    eixoZ: "0.05",
    layerHeight: "0.05 - 0.15mm",
    velocidadeImpressao: "170mm/h",
    consumo: "150W",
    anoLancamento: "2023",
    tamanho: "33x27x60",
    porte: "grande",
    area: "228x128x230",
    peso: "13",
    conectividade: "USB (2x) + Wi-fi",
    linearGuide: "Dupla",
    autoFill: true,
    autoWithdrawal: true,
    airPurifier: true,
    lcdProtector: true,
    heatVat: false,
    autoLeveling: false,
    buildPlate: "metal escovado",
    FEP: "Pictor",
    autoResume: false,
    imagem: "/img/creality/Creality Halot-Mage Pro - impressao 3d resina.webp",
    description: "Resumo em breve."
    
},  









/* ELEGOO  */
{
  id: 33,
  nome: "Mars - 2K (RGB)",
  resolucao: "2K (RGB)",
  marca: "Elegoo",
  tecnologia: "MSLA",
  fonteLuz: "UV Integrated Light",
  eixosXY: "0.047 (2560x1440)",
  eixoZ: "0.00125",
  layerHeight: "0.01 - 0.2",
  velocidadeImpressao: "22.5mm/h",
  consumo: "60W",
  anoLancamento: "2018",
  tamanho: "20x20x41",
  porte: "medio",
  area: "120x68x155",
  peso: "5kg",
  conectividade: "USB",
  linearGuide: "simples",
  autoFill: false,
  autoWithdrawal: false,
  airPurifier: false,
  lcdProtector: false,
  heatVat: false,
  autoLeveling: false,
  buildPlate: "metal escovado",
  FEP: "FEP",
  autoResume: false,
  imagem: "/img/elegoo/Elegoo Mars - impressao 3d resina.webp",
  description: "Resumo em breve."
  
},
{
  id: 34,
  nome: "Mars Pro (RGB)",
  tecnologia: "MSLA",
  marca: "Elegoo",
  resolucao: "2K (RGB)",
  fonteLuz: "UV Matrix Light",
  eixosXY: "0.047 (2560x1440)",
  eixoZ: "0.00125",
  layerHeight: "0.01 - 0.2",
  velocidadeImpressao: "22.5mm/h",
  consumo: "72W",
  anoLancamento: "2018",
  tamanho: "20x20x42",
  porte: "medio",
  area: "120x68x156",
  peso: "6.3kg",
  conectividade: "USB",
  linearGuide: "simples",
  autoFill: false,
  autoWithdrawal: false,
  airPurifier: true,
  lcdProtector: false,
  heatVat: false,
  autoLeveling: false,
  buildPlate: "metal escovado",
  FEP: "FEP",
  autoResume: false,
  imagem: "/img/elegoo/Elegoo Mars Pro - impressao 3d resina.webp",
  description: "Resumo em breve."
  
},
{
  id: 35,
  nome: "Elegoo Mars C - 2K(RGB)",
  tecnologia: "MSLA (RGB)",
  marca: "Elegoo",
  resolucao: "2K",
  fonteLuz: "",
  eixosXY: "0.047 (2560x1440)",
  eixoZ: "0.00125",
  layerHeight: "",
  velocidadeImpressao: "---",
  consumo: "40W",
  anoLancamento: "2020",
  tamanho: "",
  porte: "medio",
  area: "120x68x155",
  peso: "",
  conectividade: "USB",
  linearGuide: "",
  autoFill: false,
  autoWithdrawal: false,
  airPurifier:"",
  lcdProtector:"",
  heatVat: false,
  autoLeveling: false,
  buildPlate: "",
  FEP: "",
  autoResume: false,
  imagem: "/img/elegoo/Elegoo Mars C.webp",
  description: "Resumo em breve."
  
},
{
  id:"36",
  nome: "Saturn",
  tecnologia: "MSLA",
  marca: "Elegoo",
  resolucao: "4K",
  fonteLuz: "UV Matrix Light",
  eixosXY: "0.050 (3840x2400)",
  eixoZ: "0.00125",
  layerHeight: "0.01 - 0.15",
  velocidadeImpressao: "40mm/h",
  consumo: "96W",
  anoLancamento: "2020",
  tamanho: "28x24x44",
  porte: "grande",
  area: "192x120x200",
  peso: "10kg",
  conectividade: "USB",
  linearGuide: "Dupla",
  autoFill: false,
  autoWithdrawal: false,
  airPurifier: false,
  lcdProtector: false,
  heatVat: false,
  autoLeveling: false,
  buildPlate: "metal escovado",
  FEP: "2.0 (nFEP/PFA)",
  autoResume: false,
  imagem: "/img/elegoo/Elegoo Saturn - impressao 3d resina.webp",
  description: "Resumo em breve."
  
},
{
  id: 37,
  nome: "Mars 2 Pro",
  tecnologia: "MSLA",
  marca: "Elegoo",
  resolucao: "2K",
  fonteLuz: "COB ",
  eixosXY: "0.050 (2560x1620)",
  eixoZ: "0.00125",
  layerHeight: "0.01-0.2",
  velocidadeImpressao: "50mm/h",
  consumo: "",
  anoLancamento: "2020",
  tamanho: "20x20x41",
  porte: "medio",
  area: "129x80x160",
  peso: "6.2",
  conectividade: "USB",
  linearGuide: "simples",
  autoFill: false,
  autoWithdrawal: false,
  airPurifier: true,
  lcdProtector: false,
  heatVat: false,
  autoLeveling: false,
  buildPlate: "metal escovado",
  FEP: "FEP",
  autoResume: false,
  imagem: "/img/elegoo/Elegoo Mars 2 Pro - impressao 3d resina.webp",
  description: "Resumo em breve."

},
{
  id: 38,
  nome: "Mars 2",
  tecnologia: "MSLA",
  marca: "Elegoo",
  resolucao: "2K",
  fonteLuz: "COB",
  eixosXY: "0.050 (2560x1620)",
  eixoZ: "0.00125",
  layerHeight: "0.01-0.2",
  velocidadeImpressao: "50mm/h",
  consumo: "",
  anoLancamento: "2021",
  tamanho: "20x20x41",
  porte: "medio",
  area: "129x80x150",
  peso: "6.2",
  conectividade: "USB",
  linearGuide: "simples",
  autoFill: false,
  autoWithdrawal: false,
  airPurifier: false,
  lcdProtector: false,
  heatVat: false,
  autoLeveling: false,
  buildPlate: "metal escovado",
  FEP: "FEP",
  autoResume: false,
  imagem: "/img/elegoo/Elegoo Mars 2 - impressao 3d resina.webp",
  description: "Resumo em breve."
  
},
{
  id: 39,
  nome: "Mars 3",
  tecnologia: "MSLA",
  marca: "Elegoo",
  resolucao: "4K",
  fonteLuz: "COB + Fresnel",
  eixosXY: "0.035 (4098x2560)",
  eixoZ: "0.00125",
  layerHeight: "0.01-0.2",
  velocidadeImpressao: "50mm/h",
  consumo: "",
  anoLancamento: "2021",
  tamanho: "22x22x43",
  porte: "medio",
  area: "143x89x175",
  peso: "5.2",
  conectividade: "USB",
  linearGuide: "simples",
  autoFill: false,
  autoWithdrawal: false,
  airPurifier: false,
  lcdProtector: false,
  heatVat: false,
  autoLeveling: false,
  buildPlate: "jat. abrasivo",
  FEP: "2.0 (nFEP/PFA)",
  autoResume: false,
  imagem: "/img/elegoo/Elegoo Mars 3 - impressao 3d resina.webp",
  description: "Resumo em breve."
  
},
{
  id: 40,
  nome: "Saturn 2",
  tecnologia: "MSLA",
  marca: "Elegoo",
  resolucao: "8K",
  fonteLuz: "COB + Fresnel",
  eixosXY: "0.028 (7680x4320)",
  eixoZ: "0.00125",
  layerHeight: "0.01-0.2",
  velocidadeImpressao: "70mm/h",
  consumo: "",
  anoLancamento: "2022",
  tamanho: "30x27x56",
  porte: "grande",
  area: "218x123x250",
  peso: "11",
  conectividade: "USB",
  linearGuide: "Dupla",
  autoFill: false,
  autoWithdrawal: false,
  airPurifier: true,
  lcdProtector: true,
  heatVat: false,
  autoLeveling: false,
  buildPlate: "jat. abrasivo",
  FEP: "2.0 (nFEP/PFA)",
  autoResume: false,
  imagem: "/img/elegoo/Elegoo Saturn 2 - impressao 3d resina.webp",
  description: "Resumo em breve."
  
},
{
  id: 41,
  nome: "Mars 3 Pro",
  tecnologia: "MSLA",
  marca: "Elegoo",
  resolucao: "4K",
  fonteLuz: "COB + Fresnel",
  eixosXY: "0.035 (4098x2560)",
  eixoZ: "0.00125",
  layerHeight: "",
  velocidadeImpressao: "50mm/h",
  consumo: "",
  anoLancamento: "2022",
  tamanho: "22x22x44",
  porte: "medio",
  area: "143x90x175",
  peso: "5,5",
  conectividade: "USB",
  linearGuide: "simples",
  autoFill: false,
  autoWithdrawal: false,
  airPurifier: true,
  lcdProtector: true,
  heatVat: false,
  autoLeveling: false,
  buildPlate: "jat. abrasivo",
  FEP: "2.0 (nFEP/PFA)",
  autoResume: false,
  imagem: "/img/elegoo/Elegoo Mars 3 Pro - impressao 3d resina.webp",
  description: "Resumo em breve."
  
},
{
  id: 42,
  nome: "Jupter",
  tecnologia: "MSLA",
  marca: "Elegoo",
  resolucao: "---",
  fonteLuz: "---",
  eixosXY: "---",
  eixoZ: "---",
  layerHeight: "---",
  velocidadeImpressao: "---",
  consumo: "---",
  anoLancamento: "---",
  tamanho: "---",
  porte: "grande",
  area: "---",
  peso: "---",
  conectividade: "---",
  linearGuide: "---",
  autoFill: false,
  autoWithdrawal: false, 
  airPurifier:"---", 
  lcdProtector:"---",
  heatVat: false,
  autoLeveling: false,
  buildPlate: "---",
  FEP: "---",
  autoResume: false,
  imagem: "/img/elegoo/Elegoo Jupter - impressao 3d resina.webp",
  description: "Resumo em breve."
  
},
{
  id:43,
  nome: "Saturn S",
  tecnologia: "MSLA",
  marca: "Elegoo",
  resolucao: "4K",
  fonteLuz: "UV Matrix Light",
  eixosXY: "0.048 (4098x2560)",
  eixoZ: "0.00125",
  layerHeight: "",
  velocidadeImpressao: "70mm/h",
  consumo: "",
  anoLancamento: "2022",
  tamanho: "28x24x44",
  porte: "grande",
  area: "196x122x210",
  peso: "11",
  conectividade: "USB",
  linearGuide: "Dupla",
  autoFill: false,
  autoWithdrawal: false,
  airPurifier: true,
  lcdProtector: false,
  heatVat: false,
  autoLeveling: false,
  buildPlate: "jat. abrasivo",
  FEP: "2.0 (nFEP/PFA)",
  autoResume: false,
  imagem: "/img/elegoo/Elegoo Saturn S - impressao 3d resina.webp",
  description: "Resumo em breve."
  
},
{
  id: 44,
  nome: "Saturn 8K",
  tecnologia: "MSLA",
  marca: "Elegoo",
  resolucao: "8K",
  fonteLuz: "UV Matrix Light",
  eixosXY: "0.028 (7680x4320)",
  eixoZ: "0.00125",
  layerHeight: "0.01-0.2",
  velocidadeImpressao: "70mm/h",
  consumo: "120W",
  anoLancamento: "2022",
  tamanho: "28x24x46",
  porte: "grande",
  area: "218x123x210",
  peso: "11",
  conectividade: "USB",
  linearGuide: "Dupla",
  autoFill: false,
  autoWithdrawal: false,
  airPurifier: true,
  lcdProtector: true,
  heatVat: false,
  autoLeveling: false,
  buildPlate: "jat. abrasivo",
  FEP: "2.0 (nFEP/PFA)",
  autoResume: false,
  imagem: "/img/elegoo/Elegoo Saturn 8K -  impressao 3d resina.webp",
  description: "Resumo em breve."
  
},
{
  id: 45,
  nome: "Mars 4 DLP",
  tecnologia: "DLP",
  marca: "Elegoo",
  resolucao: "2K",
  fonteLuz: "Projetor UV",
  eixosXY: "0.050 (2560*1440)",
  eixoZ: "0.00125",
  layerHeight: "0.01-0.2",
  velocidadeImpressao: "70mm/h",
  consumo: "18W",
  anoLancamento: "2023",
  tamanho: "24x23x45",
  porte: "medio",
  area: "132x74x150",
  peso: "6.8",
  conectividade: "USB",
  linearGuide: "simples",
  autoFill: false,
  autoWithdrawal: false,
  airPurifier: true,
  lcdProtector: false,
  heatVat: false,
  autoLeveling: false,
  buildPlate: "jat. abrasivo",
  FEP: "2.0 (nFEP/PFA)",
  autoResume: false,
  imagem: "/img/elegoo/Elegoo Mars 4 DLP - impressao 3d resina.webp",
  description: "Resumo em breve."
  
},
{
  id: 46,
  nome: "Mars 4 Max",
  tecnologia: "MSLA",
  marca: "Elegoo",
  resolucao: "6k",
  fonteLuz: "COB + Refractive Light",
  eixosXY: "0.034(5700x3600)",
  eixoZ: "0.00125",
  layerHeight: "0.01-0.2",
  velocidadeImpressao: "70mm/h",
  consumo: "72w",
  anoLancamento: "2023",
  tamanho: "24x23x45",
  porte: "medio",
  area: "195x122x150",
  peso: "7.5",
  conectividade: "USB",
  linearGuide: "simples",
  autoFill: false,
  autoWithdrawal: false,
  airPurifier: true,
  lcdProtector: true,
  heatVat: false,
  autoLeveling: false,
  buildPlate: "jat. abrasivo",
  FEP: "2.0 (nFEP/PFA)",
  autoResume: false,
  imagem: "/img/elegoo/Elegoo Mars 4 Max.webp",
  description: "Resumo em breve."
  
},
{
  id: 47,
  nome: "Mars 4",
  tecnologia: "MSLA",
  marca: "Elegoo",
  resolucao: "9k",
  fonteLuz: "COB ",
  eixosXY: "0.018(8520*4320)",
  eixoZ: "0.00125",
  layerHeight: "0.01-0.2",
  velocidadeImpressao: "70mm/h",
  consumo: "72w",
  anoLancamento: "2023",
  tamanho: "22x22x43",
  porte: "medio",
  area: "153x77x175",
  peso: "5.5",
  conectividade: "USB",
  linearGuide: "simples",
  autoFill: false,
  autoWithdrawal: false,
  airPurifier: true,
  lcdProtector: true,
  heatVat: false,
  autoLeveling: false,
  buildPlate: "Gravada a laser",
  FEP: "2.0 (nFEP/PFA)",
  autoResume: false,
  imagem: "/img/elegoo/Elegoo Mars 4.webp",
  description: "Resumo em breve."
  
},
{
  id: 48,
  nome: "Mars 4 Ultra",
  tecnologia: "MSLA",
  marca: "Elegoo",
  resolucao: "9k",
  fonteLuz: "COB + Fresnel",
  eixosXY: "0.018(8520*4320)",
  eixoZ: "0.00125",
  layerHeight: "0.01-0.2",
  velocidadeImpressao: "150mm/h",
  consumo: "72w",
  anoLancamento: "2023",
  tamanho: "22x22x44",
  porte: "medio",
  area: "153x77x165",
  peso: "7",
  conectividade: "USB + WIFI",
  linearGuide: "simples",
  autoFill: false,
  autoWithdrawal: false,
  airPurifier: true,
  lcdProtector: true,
  heatVat: false,
  autoLeveling: false,
  buildPlate: "Gravada a laser",
  FEP: "ACF",
  autoResume: false,
  imagem: "/img/elegoo/Elegoo Mars 4 Ultra.webp",
  description: "Resumo em breve."
  
},
{
  id: 49,
  nome: "Saturn 3",
  tecnologia: "MSLA",
  marca: "Elegoo",
  resolucao: "12K",
  fonteLuz: "COB + Fresnel",
  eixosXY: "19*24(11520x5120)",
  eixoZ: "0.02",
  layerHeight: "0.01-0.2",
  velocidadeImpressao: "70mm/h",
  consumo: "144W",
  anoLancamento: "2023",
  tamanho: "30x27x56",
  porte: "grande",
  area: "218x122x250",
  peso: "11",
  conectividade: "USB",
  linearGuide: "Dupla",
  autoFill: false,
  autoWithdrawal: false,
  airPurifier: true,
  lcdProtector: true,
  heatVat: false,
  autoLeveling: false,
  buildPlate: "Gravada a laser",
  FEP: "ACF",
  autoResume: false,
  imagem: "/img/elegoo/Elegoo Saturn 3.webp",
  description: "Resumo em breve."
  
},
{
  id: 50,
  nome: "Saturn 3 Ultra",
  tecnologia: "MSLA",
  marca: "Elegoo",
  resolucao: "12K",
  fonteLuz: "COB + Refractive Light",
  eixosXY: "19*24(11520x5120)",
  eixoZ: "0.01",
  layerHeight: "0.01-0.2",
  velocidadeImpressao: "150mm/h",
  consumo: "180W",
  anoLancamento: "2023",
  tamanho: "30*27*56",
  porte: "grande",
  area: "218*122*260",
  peso: "12",
  conectividade: "USB + WIFI",
  linearGuide: "Dupla",
  autoFill: false,
  autoWithdrawal: false,
  airPurifier: true,
  lcdProtector: true,
  heatVat: false,
  autoLeveling: false,
  buildPlate: "Gravada a laser",
  FEP: "ACF",
  autoResume: false,
  imagem: "/img/elegoo/Elegoo Saturn 3 Ultra.webp",
  description: "Resumo em breve."
  
},









/* PHROZEN  */
{
  id: 51,
  nome: "Sonic Mini",
  resolucao: "2K",
  marca: "Phrozen",
  tecnologia: "MSLA",
  fonteLuz: "paraLED Matrix 2.0",
  eixosXY: "0.063 (1920X1080)",
  eixoZ: "---",
  layerHeight: "0.01-0.30",
  velocidadeImpressao: "50mm/h",
  consumo: "30W",
  anoLancamento: "2020",
  tamanho: "25x25x33",
  porte: "pequeno",
  area: "120x68x130",
  peso: "5",
  conectividade: "USB",
  linearGuide: "simples",
  autoFill: false,
  autoWithdrawal: false,
  airPurifier: false,
  lcdProtector: false,
  heatVat: false,
  autoLeveling: false,
  buildPlate: "metal escovado",
  FEP: "FEP",
  autoResume: false,
  imagem: "/img/phrozen/Phrozen Sonic Mini - impressao 3d resina.webp",
  description: "Resumo em breve."
  
},
{
  id: 52,
  nome: "Sonic Mini 4K",
  resolucao: "4K",
  marca: "Phrozen",
  tecnologia: "MSLA",
  fonteLuz: "paraLED Matrix 2.0",
  eixosXY: "0.035 (3840x2160)",
  eixoZ: "---",
  layerHeight: "0.01-0.30",
  velocidadeImpressao: "80mm/h",
  consumo: "40W",
  anoLancamento: "2020",
  tamanho: "25x25x33",
  porte: "pequeno",
  area: "134x75x130",
  peso: "5",
  conectividade: "USB",
  linearGuide: "simples",
  autoFill: false,
  autoWithdrawal: false,
  airPurifier: false,
  lcdProtector: false,
  heatVat: false,
  autoLeveling: false,
  buildPlate: "metal escovado",
  FEP: "FEP",
  autoResume: false,
  imagem: "/img/phrozen/Phrozen Sonic Mini 4K - lupa3d.webp",
  description: "Resumo em breve."
  
},
{
  id: 53,
  nome: "Sonic Mighty 4K",
  resolucao: "4K",
  marca: "Phrozen",
  tecnologia: "MSLA",
  fonteLuz: "paraLED Matrix 2.0",
  eixosXY: "0.052()",
  eixoZ: "---",
  layerHeight: "0.01-0.30",
  velocidadeImpressao: "80mm/h",
  consumo: "72W",
  anoLancamento: "2020",
  tamanho: "28x28x44",
  porte: "grande",
  area: "200x125x220",
  peso: "8",
  conectividade: "USB",
  linearGuide: "simples",
  autoFill: false,
  autoWithdrawal: false,
  airPurifier: false,
  lcdProtector: false,
  heatVat: false,
  autoLeveling: false,
  buildPlate: "metal escovado",
  FEP: "FEP",
  autoResume: false,
  imagem: "/img/phrozen/Phrozen Sonic Mighty 4K - impressao 3d resina.webp",
  description: "Resumo em breve."
  
},
{
  id: 54,
  nome: "Sonic Mini 8K",
  resolucao: "8K",
  marca: "Phrozen",
  tecnologia: "MSLA",
  fonteLuz: "Linear Projection LED ",
  eixosXY: "0.022",
  eixoZ: "---",
  layerHeight: "0.01-0.30",
  velocidadeImpressao: "80mm/h",
  consumo: "50W",
  anoLancamento: "2021",
  tamanho: "29x29x42",
  porte: "medio",
  area: "165x72x180",
  peso: "13",
  conectividade: "USB",
  linearGuide: "Dupla",
  autoFill: false,
  autoWithdrawal: false,
  airPurifier: false,
  lcdProtector: false,
  heatVat: false,
  autoLeveling: false,
  buildPlate: "Gravada a laser",
  FEP: "FEP",
  autoResume: false,
  imagem: "/img/phrozen/Phrozen Sonic Mini 8K - impressao 3d resina.webp",
  description: "Resumo em breve."
  
},
{
  id: 55,
  nome: "Sonic Mighty 8K",
  resolucao: "8K",
  marca: "Phrozen",
  tecnologia: "MSLA",
  fonteLuz: "Linear Projection LED ",
  eixosXY: "0.028",
  eixoZ: "---",
  layerHeight: "0.01-0.30",
  velocidadeImpressao: "70mm/h",
  consumo: "120W",
  anoLancamento: "2022",
  tamanho: "33x33x51",
  porte: "grande",
  area: "218x123x235",
  peso: "14,3",
  conectividade: "USB + WIFI + Ethernet",
  linearGuide: "simples",
  autoFill: false,
  autoWithdrawal: false,
  airPurifier: false,
  lcdProtector: false,
  heatVat: false,
  autoLeveling: false,
  buildPlate: "Gravada a laser",
  FEP: "FEP",
  autoResume: false,
  imagem: "/img/phrozen/Phrozen Sonic Mighty 8K - impressao 3d resina.webp",  
  description: 
  "A impressora Sonic Mighty 8K da marca Phrozen é uma impressora de resina de alta qualidade lançada em 2022. Ela utiliza a tecnologia MSLA com uma resolução de 8K. A fonte de luz é Linear Projection LED, oferecendo uma excelente qualidade de impressão. Os eixos XY têm uma precisão de 0.028. A impressora possui uma ampla faixa de camada de 0.01 a 0.30 mm e uma velocidade de impressão de 70 mm/h, consumindo 120W de energia. Ela é considerada de porte grande, com dimensões de 33x33x51 cm e uma área de impressão de 218x123x235 mm.   A conectividade inclui USB, WIFI e Ethernet, enquanto a build plate é Gravada a laser e utiliza F.E.P como pelicula de liberação. É uma impressora de resina de alta qualidade, adequada para projetos detalhados e precisos em 8K."
},
{
  id: 56,
  nome: "Sonic Mini 8K S",
  resolucao: "8K",
  marca: "Phrozen",
  tecnologia: "MSLA",
  fonteLuz: "Linear Projection LED ",
  eixosXY: "0.022",
  eixoZ: "---",
  layerHeight: "0.01-0.30",
  velocidadeImpressao: "80mm/h",
  consumo: "48W",
  anoLancamento: "2023",
  tamanho: "29x29x43",
  porte: "medio",
  area: "165x72x170",
  peso: "10",
  conectividade: "USB",
  linearGuide: "simples",
  autoFill: false,
  autoWithdrawal: false,
  airPurifier: false,
  lcdProtector: false,
  heatVat: false,
  autoLeveling: false,
  buildPlate: "Gravada a laser",
  FEP: "FEP",
  autoResume: false,
  imagem: "/img/phrozen/Phrozen Sonic Mini 8K S.webp",
  description: "Resumo em breve."
  
},
{
  id: 57,
  nome: "Sonic Mega 8K",
  resolucao: "8K",
  marca: "Phrozen",
  tecnologia: "MSLA",
  fonteLuz: "paraLED Matrix 3.0",
  eixosXY: "0.043",
  eixoZ: "---",
  layerHeight: "0.01-0.30",
  velocidadeImpressao: "70mm/h",
  consumo: "",
  anoLancamento: "2023",
  tamanho: "47x40x68",
  porte: "grande",
  area: "330x185x400",
  peso: "35",  
  conectividade: "USB + Ethernet",
  linearGuide:"Dupla",
  autoFill: false,
  autoWithdrawal: false,
  airPurifier: false,
  lcdProtector: false,
  heatVat: false,
  autoLeveling: false,
  buildPlate: "gravadaa laser",
  FEP: "FEP",
  autoResume: false,
  imagem: "/img/phrozen/Phrozen Sonic Mega 8K - impressao 3d resina.webp",
  description: "Resumo em breve."
  
},
{ id: 58,
  nome: "Sonic Mega 8K S",
  resolucao: "8K",
  marca: "Phrozen",
  tecnologia: "MSLA",
  fonteLuz: "paraLED Matrix 3.0",
  eixosXY: "0.043",
  eixoZ: "---",
  layerHeight: "0.01-0.30",
  velocidadeImpressao: "---",
  consumo: "240W",
  anoLancamento: "2023",
  tamanho: "47x38x56",
  porte: "grande",
  area: "330x185x300",
  peso: "26",
  conectividade: "USB",
  linearGuide: "Dupla",
  autoFill: false,
  autoWithdrawal: false,
  airPurifier: false,
  lcdProtector: false,
  heatVat: false,
  autoLeveling: false,
  buildPlate: "Gravada a laser",
  FEP: "ACF",
  autoResume: false,
  imagem: "/img/phrozen/2023 - Sonic Mega 8K S - impressao 3d resina.webp",  
  description: "A impressora de resina Sonic Mega 8K S da marca Phrozen é uma nova adição ao mercado, lançada em 2023. Ela utiliza a tecnologia MSLA (Matrix Stereo-Lithography) e oferece uma impressionante resolução de 8K. A área de impressão é generosa, com dimensões de 330x185x300 mm, permitindo a criação de peças de tamanho considerável.  Quanto à conectividade, a Sonic Mega 8K S utiliza uma conexão USB para transferência de dados. Ela possui um eixo Z não especificado, mas os eixos XY têm uma precisão de 0.043. A velocidade de impressão não foi informada, mas a build plate (plataforma de impressão) é Gravada a laser para maior durabilidade.  A fonte de luz utilizada é a paraLED Matrix 3.0, que é essencial para a cura da resina durante o processo de impressão. No geral, essa impressora oferece recursos avançados e é uma opção interessante para projetos de resina de alta qualidade em 8K."
},



/* SPARKMAKER */

  {
    id: 59,
    nome: "SparkMaker Original",
    resolucao: "720p",
    marca: "SparkMaker",
    areaImpressaoX: 98,
    areaImpressaoY: 55,
    areaImpressaoZ: 125,
    area: { x: 218, y: 123, z: 210 },
    velocidadeImpressao: 10, 
    fonteLuz: "UV-LED",
    eixoZ: "50 mm",
    eixosXY: "50µm",
    conectividade: "Wi-Fi",
    layerHeigth: "0.05mm",
    BuiltPlate: "common",
    FEP: "common",
    porte: "pequeno",
    autoFill: false,
    airPurifier: false,
    lcdProtector: false,
    heatVat: false,
    autoLeveling: false,
    manual: "manual1.pdf",
    lojas: [
      { nome: "Loja 1", link: "#" },
      { nome: "Loja 2", link: "#" },
    ],
    imagem: "/img/sparkMaker/SparkMaker Original - impressao 3d resina.webp", 
    description: "Resumo em breve.",
    anoLancamento: "2023", 
    tecnologia: "MSLA (RGB)" 
  },
  {
    id: 60,
    nome: "SparkMaker FHD",
    resolucao: "1080p",
    marca: "SparkMaker",
    areaImpressaoX: 110,
    areaImpressaoY: 61,
    areaImpressaoZ: 125,
    area: { x: 218, y: 123, z: 210 },
    velocidadeImpressao: 10, 
    fonteLuz: "UV-LED",
    eixoZ: "50 mm",
    eixosXY: "50µm",
    conectividade: "Wi-Fi",
    layerHeigth: "0.05mm",
    BuiltPlate: "common",
    FEP: "common",
    porte: "pequeno",
    autoFill: false,
    airPurifier: false,
    lcdProtector: false,
    heatVat: false,
    autoLeveling: false,
    manual: "manual1.pdf",
    lojas: [
      { nome: "Loja 1", link: "#" },
      { nome: "Loja 2", link: "#" },
    ],
    imagem: "/img/sparkMaker/SparkMaker FHD - impressao 3d resina.webp", 
    description: "Resumo em breve.",
    anoLancamento: "2023", 
    tecnologia: "MSLA" 
  },
  {
    id: 61,
    nome: "PrintHero",
    resolucao: "4K",
    marca: "SparkMaker",
    areaImpressaoX: 165,
    areaImpressaoY: 293,
    areaImpressaoZ: 400,
    area: { x: 218, y: 123, z: 210 },
    velocidadeImpressao: 10, 
    fonteLuz: "UV-LED",
    eixoZ: "50 mm",
    eixosXY: "50µm",
    conectividade: "Wi-Fi",
    layerHeigth: "0.05mm",
    BuiltPlate: "common",
    FEP: "common",
    porte: "grande",
    autoFill: false,
    airPurifier: false,
    lcdProtector: false,
    heatVat: false,
    autoLeveling: false,
    manual: "manual1.pdf",
    lojas: [
      { nome: "Loja 1", link: "#" },
      { nome: "Loja 2", link: "#" },
    ],
    imagem: "/img/sparkMaker/PrintHero - impressao 3d resina.webp", 
    description: "Resumo em breve.",
    
    anoLancamento: "2023", 
    tecnologia: "MSLA" 
  },





  {
    id: 62,
    nome: "Biqu Pixel L",
    resolucao: "4k",
    marca: "Biqu",
    tecnologia: "MSLA",
    fonteLuz: "UV Integrated Light",
    eixosXY: "0.047 (4098x2560)",
    eixoZ: "---",
    layerHeight: "0.025 - 0.03",
    velocidadeImpressao: "---",
    consumo: "210W",
    anoLancamento: "2022",
    tamanho: "29x30x56",
    porte: "grande",
    area: "196x122x220",
    peso: "19",
    conectividade: "USB",
    linearGuide: "Dupla",
    autoFill: true,
    autoWithdrawal: false,
    airPurifier: false,
    lcdProtector: false,
    heatVat: "true",
    autoLeveling: false,
    buildPlate: "metal escovado",
    FEP: "FEP",
    autoResume: false,
    imagem: "/img/biqu/Biqu Pixel L - impressao 3d resina.webp",
    description: "Resumo em breve."
    
},
  


/*
  {
    id: 1
    nome: "Form 3L",
    resolucao: "4K",
    marca: "Formlabs",
    areaImpressaoX: 335,
    areaImpressaoY: 20,
    areaImpressaoZ: 30,
    area: { x: 218, y: 123, z: 210 },
    velocidadeImpressao: 10, 
    fonteLuz: "UV-LED",
    eixoZ: "50 mm",
    eixosXY: "50µm",
    conectividade: "Wi-Fi",
    layerHeigth: "0.05mm",
    BuiltPlate: "common",
    FEP: "common",
    autoFill: false,
    airPurifier: false,
    lcdProtector: false,
    heatVat: false,
    autoLeveling: false,
    manual: "manual1.pdf",
    lojas: [
      { nome: "Loja 1", link: "#" },
      { nome: "Loja 2", link: "#" },
    ],
    imagem: "/img/formlwebp", ,
    description: "Resumo em breve."
    
    anoLancamento: "2023", 
    tecnologia: "MSLA" 
  },
*/


  // Adicione impressoras fictícias abaixo
];

